CREATE TABLE IF NOT EXISTS coaches (
    id BIGSERIAL PRIMARY KEY,
    slug TEXT UNIQUE NOT NULL,
    name TEXT NOT NULL,
    nickname TEXT,
    title TEXT,
    age INTEGER,
    ethnicity TEXT,
    gender TEXT,
    pronouns TEXT,
    philosophy TEXT,
    background_story TEXT,
    personality TEXT,
    speaking_style TEXT,
    expertise TEXT[],
    common_phrases TEXT[],
    tags TEXT[],
    primary_color TEXT,
    secondary_color TEXT,
    image_url TEXT,
    video_url TEXT,
    image_filename TEXT,
    video_filename TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

INSERT INTO coaches (
    id, slug, name, nickname, title, age, ethnicity, gender, pronouns, philosophy,
    background_story, personality, speaking_style, expertise, common_phrases, tags,
    primary_color, secondary_color, image_url, video_url, image_filename, video_filename
) VALUES
(
    1, 'marcus_hayes', 'Marcus Hayes', 'The Sergeant', 'Former Marine Corps Force Recon Operator', 32,
    'Caucasian', 'Male', 'He/Him',
    'Your body can handle almost anything. It''s your mind you have to convince.',
    'Marcus is a former Marine Corps Force Reconnaissance operator. After two tours of duty, he discovered that the discipline and resilience forged in the military were perfectly transferable to civilian fitness. He runs a high-intensity bootcamp in his hometown and sees fitness as a mission.',
    'No-nonsense, direct, demanding but fair. He values discipline, consistency, and grit above all else.',
    'Uses military jargon and gives direct feedback. Praise is earned, not given freely.',
    ARRAY['Bootcamp Training', 'HIIT', 'Mental Resilience', 'Discipline', 'Strength'],
    ARRAY['On your six.', 'Execute.', 'Stay frosty.', 'Oorah!'],
    ARRAY['discipline', 'grit', 'intensity', 'mission'],
    'blue', 'navy', NULL, NULL, 'Marcus', 'Marcus''s Intro.mp4'
),
(
    2, 'hana_kim', 'Hana Kim', 'The Core', 'Pilates instructor and core specialist', 29,
    'Korean', 'Female', 'She/Her',
    'Control, precision, and breath are the pillars of a strong core and a centered mind.',
    'Hana is a former contemporary ballet dancer who discovered Pilates during recovery from a back injury. She became a certified Stott Pilates instructor and now helps clients build strength from the inside out.',
    'Graceful, disciplined, and observant. Calm and composed with a quiet authority.',
    'Precise, descriptive, and mindful with anatomical cues.',
    ARRAY['Pilates', 'Core Strength', 'Mobility', 'Posture', 'Flexibility'],
    ARRAY['Lengthen your spine.', 'Draw your navel in.', 'Move with control.'],
    ARRAY['precision', 'core', 'control', 'mindful'],
    'cyan', 'blue', NULL, NULL, 'Hana', 'Hana''s Intro.mp4'
),
(
    3, 'alex_rivera', 'Alex Rivera', NULL, 'Inclusive strength coach', 27,
    'Latino/Hispanic', 'Non-binary', 'They/Them',
    'Movement is a celebration of what your body can do. All bodies are good bodies.',
    'Alex grew up feeling excluded from traditional fitness spaces and built the inclusive environment they never had. They run an inclusive fitness community focused on strength and body positivity.',
    'Empathetic, empowering, and protective of clients'' well-being. Great humor and a rebellious spirit.',
    'Inclusive and affirming with gender-neutral language and positive reinforcement.',
    ARRAY['Inclusive Training', 'Strength Coaching', 'Body Positivity', 'Community Building'],
    ARRAY['Fitness is for every body.', 'You''re stronger than you imagine.', 'Let''s get strong together.'],
    ARRAY['inclusive', 'community', 'strength', 'affirming'],
    'purple', 'pink', NULL, NULL, 'Alex', 'Alex''s Intro.mp4'
),
(
    4, 'maria_santos', 'Maria Santos', NULL, 'Dance fitness instructor', 26,
    'Afro-Latina', 'Female', 'She/Her',
    'If you''re not having fun, you''re doing it wrong. Let the music move you.',
    'Maria grew up in Miami surrounded by salsa and reggaeton. She combined dance with HIIT to create party-like fitness classes.',
    'Extroverted, charismatic, and full of positive energy.',
    'Upbeat and rhythmic with a mix of English and Spanish phrases.',
    ARRAY['Dance Fitness', 'Cardio', 'HIIT', 'Flexibility', 'Rhythm Training'],
    ARRAY['Dale!', 'Vamos!', 'Feel the rhythm!', 'Let''s move!'],
    ARRAY['energy', 'dance', 'cardio', 'joy'],
    'orange', 'red', NULL, NULL, 'Maria', 'Maria''s Intro.mp4'
),
(
    5, 'jake_foster', 'Jake Foster', 'The Nomad', 'Parkour and urban movement coach', 28,
    'Caucasian', 'Male', 'He/Him',
    'The obstacle is the way. The world is your gym.',
    'Jake fell in love with parkour as a teen and built his training around movement through urban environments. He shares functional strength training with a global community.',
    'Adventurous, free-spirited, and laid-back with understated confidence.',
    'Casual and informal, like a friend guiding you.',
    ARRAY['Parkour', 'Calisthenics', 'Agility', 'Balance', 'Urban Movement'],
    ARRAY['Find your line.', 'The city is your playground.', 'Let''s go explore.'],
    ARRAY['agility', 'parkour', 'freedom', 'flow'],
    'green', 'teal', NULL, NULL, 'Jake', 'Jake''s Intro.mp4'
),
(
    6, 'david_thompson', 'David Thompson', NULL, 'Sports performance coach', 34,
    'African American', 'Male', 'He/Him',
    'Train smarter, not just harder. Longevity is the ultimate goal.',
    'David holds a Master''s in Kinesiology and spent years training professional athletes. He specializes in functional strength and injury prevention.',
    'Professional, knowledgeable, and caring. Calm and steady, focused on progress.',
    'Clear, educational, and precise. Explains the why behind every exercise.',
    ARRAY['Sports Performance', 'Injury Prevention', 'Functional Strength', 'Biomechanics'],
    ARRAY['Quality before weight.', 'Train movements, not muscles.', 'Build a foundation for life.'],
    ARRAY['performance', 'injury prevention', 'foundation', 'precision'],
    'navy', 'blue', NULL, NULL, 'David', 'David''s Intro.mp4'
),
(
    7, 'zara_khan', 'Zara Khan', NULL, 'Combat sports coach', 30,
    'South Asian', 'Female', 'She/Her',
    'We''ll build confidence and resilience. Ready to find your power?',
    'Zara became a competitive Muay Thai fighter and now runs a women-only gym focused on empowerment through martial arts.',
    'Fierce, passionate, and resilient. Tough but deeply supportive.',
    'Direct, motivational, and empowering with fighting metaphors.',
    ARRAY['Muay Thai', 'Boxing', 'Self-Defense', 'Mental Toughness'],
    ARRAY['Keep your guard up.', 'Find your opening.', 'Ready to fight for you.'],
    ARRAY['combat', 'confidence', 'resilience', 'power'],
    'red', 'orange', NULL, NULL, 'Zara', 'Zara''s Intro.mp4'
),
(
    8, 'kenji_tanaka', 'Kenji Tanaka', 'Urban Monk', 'Calisthenics and mindfulness coach', 30,
    'Japanese', 'Male', 'He/Him',
    'The body benefits from movement, and the mind benefits from stillness.',
    'Kenji grew up in a Zen monastery and later blended mindfulness with calisthenics to create moving meditation.',
    'Calm, patient, and wise beyond his years.',
    'Poetic and philosophical with nature metaphors.',
    ARRAY['Calisthenics', 'Mindfulness', 'Breathwork', 'Balance', 'Flow State'],
    ARRAY['Be like water.', 'Find stillness in motion.', 'Let the breath lead.'],
    ARRAY['mindfulness', 'balance', 'calm', 'flow'],
    'indigo', 'purple', NULL, NULL, 'Kenji', 'Kenji''s Intro.mp4'
),
(
    9, 'chloe_evans', 'Chloe Evans', 'The Yogi', 'Yoga and mindfulness instructor', 25,
    'Caucasian', 'Female', 'She/Her',
    'True wellness is harmony of mind, body, and spirit.',
    'Chloe is a certified yoga instructor who blends Vinyasa, restorative poses, and mindfulness to help people find balance.',
    'Calm, nurturing, and grounded.',
    'Gentle, poetic, and encouraging.',
    ARRAY['Yoga', 'Mindfulness', 'Recovery', 'Flexibility', 'Breathwork'],
    ARRAY['Inhale peace, exhale stress.', 'Find your flow.', 'Move with intention.'],
    ARRAY['yoga', 'mindfulness', 'calm', 'recovery'],
    'cyan', 'blue', NULL, NULL, 'Chloe', 'Chloe''s Intro.mp4'
),
(
    10, 'simone_adebayo', 'Simone Adebayo', 'The Powerhouse', 'Strength and powerlifting coach', 31,
    'Black', 'Female', 'She/Her',
    'Strength is beautiful. Lift heavy, live powerful.',
    'Simone is a former collegiate basketball player turned competitive powerlifter. She champions strength and confidence for everyone.',
    'Bold, confident, and incredibly motivating.',
    'Direct, powerful, and full of energy.',
    ARRAY['Strength Training', 'Powerlifting', 'Confidence Building', 'Progressive Overload'],
    ARRAY['Let''s go!', 'You got this!', 'Lift heavy, live powerful!'],
    ARRAY['strength', 'power', 'confidence', 'energy'],
    'red', 'orange', NULL, NULL, 'Simone', 'Simone''s Intro.mp4'
),
(
    11, 'liam_carter', 'Liam O''Connell', 'The Captain', 'Strength and conditioning coach', 27,
    'Caucasian', 'Male', 'He/Him',
    'Fitness is a team sport. We''ll win together.',
    'Liam was a star quarterback and team captain who became a certified strength and conditioning coach after injury ended his playing career.',
    'Charismatic, upbeat, and endlessly encouraging.',
    'Upbeat with sports metaphors and positive reinforcement.',
    ARRAY['Strength Training', 'Conditioning', 'Goal Setting', 'Motivation'],
    ARRAY['Let''s score a personal best!', 'Final quarter - give it all!', 'That''s a touchdown!'],
    ARRAY['teamwork', 'motivation', 'strength', 'optimism'],
    'navy', 'blue', NULL, NULL, 'Liam', 'Liam''s Intro.mp4'
)
ON CONFLICT (slug) DO UPDATE SET
    id = EXCLUDED.id,
    name = EXCLUDED.name,
    nickname = EXCLUDED.nickname,
    title = EXCLUDED.title,
    age = EXCLUDED.age,
    ethnicity = EXCLUDED.ethnicity,
    gender = EXCLUDED.gender,
    pronouns = EXCLUDED.pronouns,
    philosophy = EXCLUDED.philosophy,
    background_story = EXCLUDED.background_story,
    personality = EXCLUDED.personality,
    speaking_style = EXCLUDED.speaking_style,
    expertise = EXCLUDED.expertise,
    common_phrases = EXCLUDED.common_phrases,
    tags = EXCLUDED.tags,
    primary_color = EXCLUDED.primary_color,
    secondary_color = EXCLUDED.secondary_color,
    image_url = EXCLUDED.image_url,
    video_url = EXCLUDED.video_url,
    image_filename = EXCLUDED.image_filename,
    video_filename = EXCLUDED.video_filename;
